image: w3devin/gp-neon

tasks:
  - init: |
      sudo apt install -y build-essential libtool libreadline-dev zlib1g-dev flex bison libseccomp-dev libssl-dev clang pkg-config libpq-dev etcd
       cmake postgresql-client
      make -j`nproc`
    command: |
      # initialize neon
      ./target/debug/neon_local init 

      # start pageserver and safekeeper
      ./target/debug/neon_local start

      # start postgres compute node
      ./target/debug/neon_local pg start main
      
      # check list of running postgres instances
      ./target/debug/neon_local pg list


vscode:
  extensions:
    - cweijan.vscode-database-client2